version: 3

pullapprove_conditions:
- "'Needs Review' in labels"

groups:
  code_review:
    reviewers:
      users:
      - carlos-lopez-garces
      - mattsonic
      - elfrank
    reviews:
      required: 2
      request: 2