version: 3

pullapprove_conditions:
  - condition: "'Needs Review' in labels"
    unmet_status: pending
    explanation: "Work in progress"

groups:
  code_review:
    reviews:
      required: 2
      request: 1
      request_order: random
    reviewers:
      users:
        - carlos-lopez-garces
        - mattsonic
        - dvaldivia
        - elfrank